### ISSUE TITLE
Complex timestamp with letter at the end returns incorrect regex

### ISSUE THREAD

**Issue by menshka** [dbuhlbrown/Regex-Generator#1]
Here is timestamp I used
2021-05-26T20:52:38.000Z

This is what returned: 
\d{4}[-]\d{2}[-]\d{2}\w{1}\d{2}[:]\d{2}[:]\d{2}[.]\d{4}
And it should:
\d{4}[-]\d{2}[-]\d{2}\w{1}\d{2}[:]\d{2}[:]\d{2}[.]\d{3}\w{1}

**Comment by dbuhlbrown** [comment]
Hey, I just noticed this issue was open. I'll take a look at it, thanks for letting me know.

**Comment by dbuhlbrown** [comment]
I fixed the issue. Thanks for letting me know about it. The changes are live now.
